name: testing assignment

on:
  push:
    branches:
      - test_case

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: run tests and generate report
        run: |
          echo "Running tests..."
          npm run test --verbose || true
          echo "Tests completed. Check the log above for details."


      - name: Run coverage and send it to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coverage

